"""
Django settings for habit_tracker project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'user',
    'habits',
    'groups'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'common.middleware.OptionalApiTrailingSlash',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'habit_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'habit_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env("DB_ENGINE"),
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        "OPTIONS": {"sslmode": "require"},
    }
}

# DEFAULT_AUTO_FIELD = "django_mongodb_backend.fields.ObjectIdAutoField"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "user.User"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
}

# Sign in with Google
#
# The whole exchange is server side, so the browser never sees the client secret
# and no Google credential is exposed through a NEXT_PUBLIC_ variable. The
# browser is handed to Google by a redirect from `/api/user/auth/google/start/`
# and comes back to `/api/user/auth/google/callback/`, which mints SimpleJWT and
# redirects to `SUCCESS_URL` with the tokens in the URL fragment.
#
# REDIRECT_URI must be the URL the *browser* reaches, which is normally the
# Next.js origin because the callback is proxied through /api like every other
# call, not the Django host. SUCCESS_URL is the page on the frontend that adopts
# the session.
#
# Every value defaults to empty so the project still boots - and the test suite
# still runs - with no Google project configured at all.
GOOGLE_OAUTH = {
    "CLIENT_ID": env("GOOGLE_CLIENT_ID", default=""),
    "CLIENT_SECRET": env("GOOGLE_CLIENT_SECRET", default=""),
    "REDIRECT_URI": env("GOOGLE_REDIRECT_URI", default=""),
    "SUCCESS_URL": env("GOOGLE_LOGIN_SUCCESS_URL", default=""),
    # How long a signed `state` blob stays acceptable. Long enough to survive a
    # consent screen and a password manager detour, short enough that a
    # captured callback URL is not useful for long.
    "STATE_MAX_AGE": 600,
}

GOOGLE_OAUTH_ENABLED = all(
    GOOGLE_OAUTH[key] for key in ("CLIENT_ID", "CLIENT_SECRET", "REDIRECT_URI", "SUCCESS_URL")
)

# Whether a Google login may adopt an existing account that owns the same email.
#
# Google proves control of the address, which is normally taken as proof of
# identity. This project has no email verification, so a password sign-up may
# have claimed an address its author never controlled; with this on, that
# author can later be signed into by whoever really owns the address. Turning it
# off makes a collision a 411 that points the user at password sign-in instead.
GOOGLE_LINK_EXISTING_ACCOUNTS = env.bool("GOOGLE_LINK_EXISTING_ACCOUNTS", default=True)