# Generated by Django 6.0.7 on 2026-09-30 09:54

import common.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True, null=True)),
                ('duration_type', models.CharField(choices=[('INDEFINITE', 'Indefinite'), ('FIXED', 'Fixed')], default='INDEFINITE', max_length=20)),
                ('start_date', models.BigIntegerField()),
                ('end_date', models.BigIntegerField(blank=True, null=True)),
                ('reminder', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active')], default='ACTIVE', max_length=20)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.BigIntegerField(default=common.utils.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.utils.get_unix_timestamp)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habits', to='habits.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('CUSTOM', 'Custom')], default='DAILY', max_length=20)),
                ('target_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=common.utils.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.utils.get_unix_timestamp)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='habits.habit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.BigIntegerField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=common.utils.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.utils.get_unix_timestamp)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['habit', 'date'], name='habit_log_habit_date_idx'), models.Index(fields=['habit', 'status'], name='habit_log_habit_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_log_per_day')],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'status'], name='habits_habi_user_id_04e2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'start_date'], name='habits_habi_user_id_173195_idx'),
        ),
    ]
