# Generated by Django 6.0.7 on 2026-09-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_tag_user_alter_habitlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped')], default='ACTIVE', max_length=20),
        ),
    ]
