# Generated by Django 6.0.7 on 2026-10-02 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_deleted'], name='habit_user_deleted_idx'),
        ),
    ]
