# Generated by Django 6.0.7 on 2026-10-02 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('habits', '0004_habit_habit_user_deleted_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='challenge_ended_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='challenge_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='habit',
            name='challenge_started_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='challenge_started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='challenge_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='challenge_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='challenge_winner_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='groups.group'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
