# Generated by Django 6.0.7 on 2026-10-02 08:53

import common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('habits', '0005_habit_challenge_ended_at_habit_challenge_rules_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscribed_at', models.BigIntegerField(default=common.utils.get_unix_timestamp)),
                ('created_at', models.BigIntegerField(default=common.utils.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.utils.get_unix_timestamp)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['group', 'is_challenge'], name='habit_group_chal_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['group', 'challenge_status'], name='habit_chal_status_idx'),
        ),
        migrations.AddField(
            model_name='challengesubscription',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='habits.habit'),
        ),
        migrations.AddField(
            model_name='challengesubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='challengesubscription',
            index=models.Index(fields=['challenge'], name='csub_challenge_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubscription',
            index=models.Index(fields=['user'], name='csub_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengesubscription',
            unique_together={('challenge', 'user')},
        ),
    ]
