# Generated by Django 6.0.7 on 2026-10-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('habits', '0006_challengesubscription_habit_habit_group_chal_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='challenge_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participation_copies', to='habits.habit'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['challenge_source'], name='habit_chal_source_idx'),
        ),
    ]
