# Generated by Django 6.0.7 on 2026-10-02 06:38

import common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('join_requests_enabled', models.BooleanField(default=True)),
                ('members_can_invite', models.BooleanField(default=True)),
                ('anyone_can_create_challenge', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.BigIntegerField(default=common.utils.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.utils.get_unix_timestamp)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('expires_at', models.BigIntegerField(blank=True, null=True)),
                ('responded_at', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=common.utils.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.utils.get_unix_timestamp)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.group')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('responded_at', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=common.utils.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.utils.get_unix_timestamp)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_join_requests', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='groups.group')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.BigIntegerField(default=common.utils.get_unix_timestamp)),
                ('created_at', models.BigIntegerField(default=common.utils.get_unix_timestamp, editable=False)),
                ('updated_at', models.BigIntegerField(default=common.utils.get_unix_timestamp)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['owner'], name='group_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_deleted'], name='group_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['email', 'status'], name='gi_email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['token'], name='gi_token_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['group', 'status'], name='gi_group_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['group', 'status'], name='gjr_group_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['to_user', 'status'], name='gjr_to_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['from_user', 'status'], name='gjr_from_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupjoinrequest',
            unique_together={('group', 'from_user', 'to_user', 'status')},
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'role'], name='gm_group_role_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user'], name='gm_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
    ]
